version: '2.1'
services:
#    schema-example-app:
#        container_name: schema-example-app
#        build:
#            context: .
#            dockerfile: Dockerfile
#        volumes:
#            - ./db.json:/db/db.json
#        env_file:
#            - .env
#        ports:
#            - "8080:80"
#        depends_on:
#            - schema-example-db
#            - kafka
#            - schema-example-zookeeper

    kafka:
        container_name: schema-example-kafka
        image: confluentinc/cp-kafka
        ports:
            - 9092:9092
        environment:
            KAFKA_ZOOKEEPER_CONNECT: schema-example-zookeeper:2181
            KAFKA_NUM_PARTITIONS: 10
            KAFKA_COMPRESSION_TYPE: gzip
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
            KAFKA_JMX_PORT: 9091
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

            # procotol needs to be called PLAINTEXT due to bug in schema-registry, see below
            KAFKA_LISTENERS: PLAINTEXT://kafka:29092,EXTERNAL_PLAINTEXT://kafka:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,EXTERNAL_PLAINTEXT://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL_PLAINTEXT:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        depends_on:
            schema-example-zookeeper:
                condition: service_started
        links:
            - schema-example-zookeeper
        healthcheck:
            test: "nc -z localhost 9092"
            interval: 10s
            timeout: 5s
            retries: 15

    schema-example-kafkahq:
        container_name: schema-example-kafkahq
        links:
            - schema-example-zookeeper
        image: tchiotludo/kafkahq
        ports:
            - 9090:8080
        environment:
            KAFKAHQ_CONFIGURATION: |
                kafkahq:
                  connections:
                    docker-kafka-server:
                      properties:
                        bootstrap.servers: "kafka:9092"

    schema-example-zookeeper:
        container_name: schema-example-zookeeper
        image: confluentinc/cp-zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181

    schema-example-schema-registry:
        container_name: schema-example-schema-registry
        image: confluentinc/cp-schema-registry
        depends_on:
            - kafka
            - schema-example-zookeeper
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: schema-example-zookeeper:2181
            SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
            # bug re this: https://github.com/confluentinc/schema-registry/issues/648
            SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
            SCHEMA_REGISTRY_DEBUG: "true"
        ports:
            - "8081:8081"